version: '3.7'

volumes:
  postgres_data: {}
  git_repos: {}
  redmine_files: {}
  
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=redmine
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=picksomethingyourselfandhideit
  redmine:
    build: .
    depends_on:
      - db
    volumes:
      - git_repos:/home/git
      - redmine_files:/usr/src/redmine/files
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PORT=5432
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=picksomethingyourselfandhideit
    ports:
      - target: 22
        published: 2222
        protocol: tcp
        mode: host
      - target: 3000
        published: 8080
        protocol: tcp
        mode: host
