version: '3.7'

volumes:
  git_repos: {}
  redmine_files: {}
  
services:
  redmine:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - git_repos:/home/git
      - redmine_files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      #We migrate plugins every restart, this must be true at least
      #the first time the container is spun up (with a working
      #database connection)
      REDMINE_PLUGINS_MIGRATE: 1
    ports:
      - target: 22
        published: 2222
        protocol: tcp
        mode: host
      - target: 3000
        published: 8080
        protocol: tcp
        mode: host

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
